const mongoose = require('mongoose');

const reelSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    videoUrl: {
      type: String,
      required: [true, 'Video URL is required'],
    },
    caption: {
      type: String,
      default: '',
      maxlength: [2200, 'Caption cannot exceed 2200 characters'],
    },
    audioTrackName: {
      type: String,
      default: 'Original Audio',
    },
    likes: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    saves: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    sharesCount: {
      type: Number,
      default: 0,
    },
    viewsCount: {
      type: Number,
      default: 0,
    },
    location: {
      type: String,
      default: '',
    },
    collaborators: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    taggedPeople: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    altText: {
      type: String,
      default: '',
    },
    autoGeneratedCaptions: {
      type: Boolean,
      default: false,
    },
    hideLikeAndViewCounts: {
      type: Boolean,
      default: false,
    },
    turnOffCommenting: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

const Reel = mongoose.model('Reel', reelSchema);

module.exports = Reel;
